baseURL = "https://blog.jfo.click/"
languageCode = "en-us"
title = "blog.jfo.click"

pygmentsUseClasses = true
pygmentscodefences = true

theme = "jfo"

rssLimit = 3
[outputFormats.RSS]
    baseName = "feed"

[permalinks]
    post= "/:title/"

[taxonomies]
    tag = ""
    group = ""
    category = ""
    post = ""
