# pandoc ./resume.md -o ./static/jeff_fowler_resume.pdf -V geometry:"top=2cm, bottom=1.5cm, left=4cm, right=4cm"

baseURL = "https://blog.jfo.click/"
languageCode = "en-us"
title = "blog.jfo.click"

pygmentsuseclasses = true
pygmentscodefences = true

theme = "jfo"

rssLimit = 3
[outputFormats.RSS]
    baseName = "feed"

[permalinks]
    post= "/:title/"

[taxonomies]
    tag = ""
    group = ""
    category = ""
    post = ""
