baseURL = "https://blog.jfo.click/"
languageCode = "en-us"
title = "blog.jfo.click"

pygmentsUseClasses = true
pygmentscodefences = true

# should be able to use chroma in next release, see:
# https://discourse.gohugo.io/t/differences-between-hugo-builtin-chroma-and-standalone-chroma/8644
pygmentsUseClassic = true

theme = "jfo"

[params]
    dev = true

rssLimit = 3
[outputFormats.RSS]
    baseName = "feed"

[permalinks]
    post= "/:title/"

[taxonomies]
    tag = ""
    group = ""
    category = ""
    post = ""
